I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 516, in script
    show s13p1 zoom 0.5
Exception: Image 's13p1' does not accept attributes 'zoom 0 .5'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 516, in script
    show s13p1 zoom 0.5
  File "E:\renpy-8.2.1-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "E:\renpy-8.2.1-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "E:\renpy-8.2.1-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "E:\renpy-8.2.1-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "E:\renpy-8.2.1-sdk\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "E:\renpy-8.2.1-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 's13p1' does not accept attributes 'zoom 0 .5'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
The Eve Of Lilith 0.1.0-Prologue
Sat May 18 21:53:49 2024
